### ISSUE TITLE
searchbar on profile page

### ISSUE THREAD

**Issue by abhinavsri360** [akashraj9828/gitstats#59] opened 2020-05-31 11:45 UTC
**Describe the bug**
Searchbar present on profile page does not work. I tried opening my GitStats and from there tried accessing the GitStats profile of another Github user but, the search bar was not working.
**To Reproduce**

**Expected behavior**
Searchbar on the profile page must link to the user searched.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would like to work on this bug. :smile:

**Comment by akashraj9828** [comment] 2020-05-31 15:13
Glad to know you'd like to work on it. 

This is how you can push the code.
- Fork the repo.
- Make changes in development branch. 
- Once done open a PR on `development` branch not master.
- I'll review it and merge into Master asap

Thanks for pointing out the issue.

**Comment by abhinavsri360** [comment] 2020-05-31 15:17
Sure @akashraj9828 I'll fix and push changes soon

**Comment by akashraj9828** [comment] 2020-05-31 15:20
@abhinavsri360  While checking this isse i also noticed that the search results are not hiding when searchbar goes out of focus. Can you fix that as well while you work on this.?🤔

**Comment by abhinavsri360** [comment] 2020-05-31 15:22
I will surely try to fix that

**Comment by akashraj9828** [comment] 2020-05-31 15:22
Thanks

**Comment by abhinavsri360** [comment] 2020-05-31 15:28
The hiding issue happens with the home page as well, did you notice that?

**Comment by akashraj9828** [comment] 2020-05-31 16:48
It was not happening earlier. I think something broke while making changes. If you could fix that too that would be great.

**Comment by abhinavsri360** [comment] 2020-05-31 21:10
Hey @akashraj9828 I tried fixing the issue and found that there was a minor bug i.e., 'href' was present instead of 'to' though I have fixed that the page does not loads when I click on the user I have attached a pic below which shows that the list item contained the correct link but was not loading when I was clicking that... can you figure out why?
![Screenshot (43)](https://user-images.githubusercontent.com/44001310/83362741-3a3f7e80-a3b1-11ea-9517-faf7a8ad6016.png)

**Comment by abhinavsri360** [comment] 2020-05-31 21:14
Also, I tried hiding the list but there was an issue along i.e., when focus from search bar goes off then the list also vanishes before I click the desired list item.
Though I have pushed some minor fixes and indentation fixes in some files. Please let me know if you find a way out, I am trying from my side along.

**Comment by akashraj9828** [comment] 2020-05-31 21:19
Alright I'll see what's the issue in morning. Thanks for trying.

**Comment by abhinavsri360** [comment] 2020-06-01 08:54
Hey @akashraj9828 why have you not used class components to render some minute components I mean with class components it is easier imo to debug. Is there anything special about functional components?

**Comment by akashraj9828** [comment] 2020-06-01 09:23
I have used functional components where state is not required.

Btw when I did this project i just started with react and there are many things done the wrong way and there are lots of anti patterns.


But as since I'm much more experienced in react i can say yeah i feel like functional components are better than class component since the introduction of React hooks.

React hooks provide a very neat way of managing state in a functional component.

**Comment by abhinavsri360** [comment] 2020-06-01 09:30
Ohh, on the other hand, I find hooks pretty confusing and hard to resolve when conflicts occur, can you suggest me some good documentation on Hooks in React?

**Comment by akashraj9828** [comment] 2020-06-01 18:02
I mostly refered the react official documentation for learning Hooks. 

Maybe you're using `useState` without `useEffect` hook this is the first mistake I made while using hooks.

**Comment by akashraj9828** [comment] 2020-06-01 18:15
> Hey @akashraj9828 I tried fixing the issue and found that there was a minor bug i.e., 'href' was present instead of 'to' though I have fixed that the page does not loads when I click on the user I have attached a pic below which shows that the list item contained the correct link but was not loading when I was clicking that... can you figure out why?

I also couldn't figure out why it was happening so i just did a dirty fix and replaced `Link` tag by a normal `a` tag so that page will force refresh when clicked on it. Not the best approach xD but this entire project is a mess lol.

Go ahead and close the issue if you think the issue is fixed.

**Comment by abhinavsri360** [comment] 2020-06-01 18:18
I think you haven't pushed the changes to the hosted site, because I don't find it working as it is expected 👁️‍🗨️

**Comment by abhinavsri360** [comment] 2020-06-01 18:21
Also, why don't you use Netlify to host the project? Netlify is pretty cool and user friendly imo

**Comment by akashraj9828** [comment] 2020-06-01 18:25
> I think you haven't pushed the changes to the hosted site, because I don't find it working as it is expected 👁️‍🗨️

Force refresh the browser. You might be checking the cached version of app

**Comment by akashraj9828** [comment] 2020-06-01 18:26
> Also, why don't you use Netlify to host the project? Netlify is pretty cool and user friendly imo

Netlify is great but i had my own server so why not use it. When using my own server I have more flexibility. If i didn't had my own server then netlify would have been my first choice as well.

**Comment by abhinavsri360** [comment] 2020-06-01 18:27
Yes, it's working now

**Closed** 2020-06-01 18:28 UTC
Labels: bug

**Comment by abhinavsri360** [comment] 2020-06-01 18:53
> > Also, why don't you use Netlify to host the project? Netlify is pretty cool and user friendly imo
> 
> Netlify is great but i had my own server so why not use it. When using my own server I have more flexibility. If i didn't had my own server then netlify would have been my first choice as well.

That's awesome, learned a lot in past 30 hours
